name: sparkle api gateway pipeline

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker container
        run: docker build -t sparkle-api-gateway --file ./misc/Dockerfile . 
      - name: Run integration tests
        run: ./bin/run_integration_tests.sh
            
