name: sparkle-api-gateway ci pipeline

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set scripts permissions
        run: chmod 777 ./bin/*.sh
      - name: Update dependencies
        run: ./bin/deps.sh
      - name: Set up virtual env
        run: ./bin/venv.sh
      - name: Run unit tests
        run: ./bin/run_unit_tests.sh
      - name: Build docker container
        run: docker build -t sparkle-api-gateway --file ./misc/Dockerfile .
      - name: Create docker network
        run: docker network create sparkle-net
      - name: Fetch sparkle-db scheme:
        run: |
            git clone --single-branch --branch https://github.com/sparkle-sh/sparkle-db .
            ln -s /sparkle-db/misc test_misc
      - name: Run integration tests
        run: ./bin/run_integration_tests.sh
        env:
          SPARKLE_TEST_ENV: 1
      - name: Push docker container
        if: github.ref == 'refs/heads/dev'
        run: |
          docker login --username ${{ secrets.DOCKER_AUTH_LOGIN }} --password ${{ secrets.DOCKER_AUTH_TOKEN}}
          docker tag sparkle-api-gateway ${{ secrets.DOCKER_AUTH_LOGIN }}/sparkle-api-gateway
          docker push ${{ secrets.DOCKER_AUTH_LOGIN }}/sparkle-api-gateway
